// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoSpe_KnfSne5zWGPHikX69AJfP_lfoc',
    appId: '1:309460142389:web:b0eca050d332527ec2e47c',
    messagingSenderId: '309460142389',
    projectId: 'kmitl-telemedicine-66950013',
    authDomain: 'kmitl-telemedicine-66950013.firebaseapp.com',
    storageBucket: 'kmitl-telemedicine-66950013.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAte1PDc7tVOxo1HBUp0e95Gz9hu-5OA-4',
    appId: '1:309460142389:android:aed74f3afa7f0aa2c2e47c',
    messagingSenderId: '309460142389',
    projectId: 'kmitl-telemedicine-66950013',
    storageBucket: 'kmitl-telemedicine-66950013.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQtN2OV0FB2Trh-4VxSw80ZG-Qt349HEo',
    appId: '1:309460142389:ios:5588706633d64f4fc2e47c',
    messagingSenderId: '309460142389',
    projectId: 'kmitl-telemedicine-66950013',
    storageBucket: 'kmitl-telemedicine-66950013.appspot.com',
    iosClientId:
        '309460142389-2bu3cse5gaosos67tmjm3ikgeigd3386.apps.googleusercontent.com',
    iosBundleId: 'com.example.kmitlTelemedicinePatient',
  );
}
