include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  errors:
    # https://pub.dev/packages/freezed#disabling-invalid_annotation_target-warning-and-warning-in-generates-files
    invalid_annotation_target: ignore
  exclude:
    # https://github.com/rrousselGit/freezed/issues/481#issuecomment-1208075701
    - "**/*.g.dart"
